### ISSUE TITLE
Create external DB settings.   

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/VREPaaS#62]
If we want to use an external DB ig. PostgreSQL we need to set it in production settings

**Comment by gpelouze** [comment]
- [ ] Merge https://github.com/QCDIS/VREPaaS/tree/62-create-external-db-settings into https://github.com/QCDIS/VREPaaS/tree/20-vre-catalog-prototype
- [ ] Modify django production settings to use PostGIS instead of SQLite
- [ ] Any other modifications? (Excluding files in k8s/ as these will be part of the Helm Charts)

**Comment by gpelouze** [comment]
Closed by https://github.com/QCDIS/VREPaaS/pull/49/commits/183cc0fd132374cca7fab83a9fb3907ef64f46bc
